# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c7bfb17648cb59802f1c553cb6ad492"
name = "Referral Program"
application_url = "https://personalized-pool-referrals-v2.fly.dev"
embedded = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["customers/create"]
  uri = "/webhooks/customers/create"

  [[webhooks.subscriptions]]
  topics = ["customers/update"]
  uri = "/webhooks/customers/update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = ["subscription_contracts/cancel"]
  uri = "/webhooks/subscription/cancelled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_discounts,read_orders,write_orders,write_products,read_own_subscription_contracts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://personalized-pool-referrals-v2.fly.dev/auth/callback",
  "https://personalized-pool-referrals-v2.fly.dev/auth/shopify/callback",
  "https://personalized-pool-referrals-v2.fly.dev/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = false
