# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "588a0a0df966b5e580184e0011d930dc"
name = "Referral Program"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_discounts,read_orders,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = false
